name: community_board

services:
    web:
        build: .
        ports:
            - '4000:4000'
        depends_on:
            db:
                condition: service_healthy
        environment:
            PORT: 4000
            RUN_MODE: logs
            DB_HOST: db
            DB_PORT: 3306
            DB_USER: root
            DB_PASS: some_password
            DB_NAME: community_board
    db:
        image: 'mysql'
        environment:
            MYSQL_ROOT_PASSWORD: some_password
            MYSQL_DATABASE: community_board
        ports:
            - '3308:3306'
        volumes:
            - db-data:/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            interval: 10s
            timeout: 5s
            retries: 3
volumes:
    db-data:
